import { stringify as yamlStringify } from 'yaml';
import type { GeneratedAdapter, GeneratedCapability } from '../types.js';

/**
 * Emit a commented `.tcp-adapter.yaml`.
 *
 * The comments are the point. This file becomes policy: the risk level a
 * generator guesses is a *suggestion*, and a human is expected to review it.
 * A plain `YAML.stringify` produces a file nobody can review, so the emitter
 * writes the reasoning inline — why each risk level was chosen, which rule
 * fired, and any suggestion for conditional rules.
 *
 * Implementation: we compose a plain object whose string values carry
 * newline-prefixed `#` comment lines. `yaml` renders multi-line scalars as
 * block literals by default, but we request `blockQuote`/literal style so the
 * comments read naturally rather than as escaped `\n`. To stay predictable we
 * emit the header and per-capability comment blocks ourselves and keep the
 * machine-readable structure exact.
 */

export interface EmitMeta {
  /** The spec source: a URL, a path, or `<stdin>`. */
  source: string;
  /** CLI version, stamped into the header. */
  version: string;
  /** When true, add a banner marking this a regeneration. */
  regenerated?: boolean;
}

const HEADER_RULE = '#'.repeat(78);

function commentBlock(lines: string[]): string {
  return lines
    .filter((line) => line.trim().length > 0)
    .map((line) => `# ${line}`)
    .join('\n');
}

/**
 * Render the YAML for a generated adapter.
 */
export function emitYaml(adapter: GeneratedAdapter, meta: EmitMeta, legacy = false): string {
  void legacy;
  const grouped = groupByTag(adapter.capabilities);

  const lines: string[] = [];

  // ------------------------------------------------------------------ header
  lines.push(HEADER_RULE);
  lines.push(`# Generated by tcpctl v${meta.version} from ${meta.source}`);
  if (meta.regenerated) {
    lines.push('# Regenerated: capabilities from the source spec were refreshed.');
    lines.push(
      '# Human-assigned risk levels, approval_required and agent_forbidden were PRESERVED.',
    );
  }
  lines.push('#');
  lines.push('# Review every risk level before deploying. This file is policy:');
  lines.push('#   risk: low                          -> executes immediately for an agent');
  lines.push('#   risk: medium + approval_required   -> a human approves the exact payload first');
  lines.push('#   risk: high  + agent_forbidden      -> agents are blocked outright');
  lines.push('#');
  lines.push('# content_risk marks responses that carry third-party free text. The kernel');
  lines.push('# prompt-injection-scans those before an agent can read them.');
  lines.push('#');
  lines.push('# Docs: https://docs.tcpcore.dev/concepts/risk-model');
  lines.push(HEADER_RULE);

  if (adapter.warnings.length > 0) {
    lines.push('');
    lines.push(commentBlock(['WARNINGS', ...adapter.warnings.map((w) => `- ${w}`)]));
  }

  // ------------------------------------------------------------------- body
  const document: Record<string, unknown> = {
    name: adapter.name,
    display_name: adapter.displayName,
    base_url: adapter.baseUrl,
    auth: buildAuth(adapter),
  };

  lines.push('');
  lines.push(yamlStringify(document, { lineWidth: 0 }).trimEnd());

  lines.push('');
  lines.push('capabilities:');

  for (const [tag, capabilities] of grouped) {
    lines.push('');
    lines.push(`  # ${'-'.repeat(72)}`);
    lines.push(`  # ${tag} (${capabilities.length})`);
    lines.push(`  # ${'-'.repeat(72)}`);

    for (const capability of capabilities) {
      lines.push('');
      // Comments sit at the item's own indentation, immediately above the `-`.
      lines.push(indent(commentBlock(capabilityComments(capability)), 2));
      lines.push(renderListItem(renderCapability(capability), 2));
    }
  }

  return `${lines.join('\n')}\n`;
}

function buildAuth(adapter: GeneratedAdapter): Record<string, unknown> {
  const auth: Record<string, unknown> = { type: adapter.authType, source: 'credential_store' };

  if (adapter.authHeader) auth.header = adapter.authHeader;
  if (adapter.authPrefix) auth.prefix = adapter.authPrefix;
  if (adapter.tokenEndpoint) auth.token_endpoint = adapter.tokenEndpoint;
  if (adapter.scopes && adapter.scopes.length > 0) auth.scopes = adapter.scopes;

  if (adapter.authType === 'jwt') {
    auth.source = 'agent_token';
    delete auth.token_endpoint;
  }

  return auth;
}

function capabilityComments(capability: GeneratedCapability): string[] {
  const lines: string[] = [];
  lines.push(
    `${capability.method} ${capability.pathTemplate} — ${capability.riskLevel.toUpperCase()} RISK`,
  );
  for (const note of capability.notes) lines.push(note);

  if (capability.agentForbidden) {
    lines.push('BLOCKED to agents. Only a human may execute this capability.');
  } else if (capability.riskLevel === 'medium' || capability.approvalRequired) {
    lines.push('A HUMAN MUST APPROVE each invocation before it executes.');
  }

  return lines;
}

/**
 * Render one capability as YAML at a fixed indentation. Keys are emitted in the
 * canonical order the adapter schema documents, so diffs stay small.
 */
function renderCapability(capability: GeneratedCapability): string {
  const ordered: Record<string, unknown> = {
    name: capability.name,
    method: capability.method,
    path: capability.pathTemplate,
    description: capability.description,
    risk: capability.riskLevel,
  };

  if (capability.approvalRequired) ordered.approval_required = true;
  if (capability.agentForbidden) ordered.agent_forbidden = true;
  if (capability.contentRisk) ordered.content_risk = capability.contentRisk;
  if (capability.deprecated) ordered.deprecated = true;

  ordered.input = capability.input;
  if (capability.output) ordered.output = capability.output;

  return yamlStringify(ordered, { lineWidth: 0, sortMapEntries: false }).trimEnd();
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => (line.length > 0 ? `${pad}${line}` : line))
    .join('\n');
}

/**
 * Render a capability as a YAML sequence item.
 *
 * The first line carries the `-` indicator and every following line is indented
 * by two extra spaces so the mapping stays a single sequence entry. Emitting a
 * bare mapping here would produce duplicate top-level keys — the bug this
 * function exists to prevent.
 */
function renderListItem(rendered: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  const continuation = ' '.repeat(spaces + 2);
  const [first = '', ...rest] = rendered.split('\n');

  return [
    `${pad}- ${first}`,
    ...rest.map((line) => (line.length > 0 ? `${continuation}${line}` : line)),
  ].join('\n');
}

/**
 * Group capabilities by their first tag, keeping declaration order within a
 * group. Untagged capabilities collect under `default`. Groups are ordered by
 * first appearance so the output mirrors the spec's own section order rather
 * than an arbitrary alphabetical one.
 */
export function groupByTag(
  capabilities: GeneratedCapability[],
): Array<[string, GeneratedCapability[]]> {
  const groups = new Map<string, GeneratedCapability[]>();

  for (const capability of capabilities) {
    const tag = capability.tags[0]?.trim() || 'default';
    const bucket = groups.get(tag);
    if (bucket) bucket.push(capability);
    else groups.set(tag, [capability]);
  }

  return [...groups.entries()];
}

/** The `tcpctl init` scaffold template (spec 1.6). */
export function emitTemplate(name: string, baseUrl: string): string {
  return `# ${name} adapter
# Generated by tcpctl init
#
# A capability is one governed action an agent may take against this API.
# Everything an agent can reach must be declared here — nothing else is exposed.

name: ${name}
display_name: ${name}
base_url: ${baseUrl}
auth:
  type: bearer
  header: Authorization
  source: credential_store

capabilities:
  - name: ping
    method: GET
    path: /ping
    description: Health check. Read-only, so it executes immediately.
    risk: low
    input:
      type: object
      properties: {}
      additionalProperties: false
`;
}
